<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%loan_car_change}}".
 *
 * @property integer $id
 * @property string $change_no
 * @property integer $loan_id
 * @property integer $customer_id
 * @property integer $car_id
 * @property integer $car_id_new
 * @property integer $apply_time
 * @property integer $manager_id
 * @property string $remark
 * @property integer $audit_at
 * @property integer $audit_by
 * @property integer $status
 * @property integer $order
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $car_audit_money
 * @property integer $min_change_money
 *
 */
class LoanCarChange extends \yii\db\ActiveRecord
{


    const  CARASSESS = 3;     //车辆评估
    const  CARASSESSAUDIT = 4;     //总部核价
    const  CARCONTROL = 5;     //车辆监管
    const  CARASSESSADD = 6;     //车辆补质

    const  LOANSTOP = -10;    //中止
    const  LOANCLOSE = 10;   //还清

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%loan_car_change}}';
    }

    public static function  getStatus()
    {
        return [

            '3' => '待评估',
            '4' => '待核价',
            '5' => '待监管',
            '6' => '待补质',
            '-10' => '终止',
            '10' => '结束',
        ];
    }



    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['change_no','min_change_money','car_id'], 'required'],
            [['loan_id', 'customer_id', 'car_id', 'car_id_new', 'apply_time', 'manager_id', 'audit_at', 'audit_by', 'status', 'order', 'created_by'], 'integer'],
            [['change_no'], 'string', 'max' => 20],
            [['remark'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => '自动增长ID',
            'change_no' => '业务编号',
            'loan_id' => '借款单号',
            'min_change_money' => '置换车辆最少价值',
            'car_audit_money' => '置换车辆审核价格',
            'customer_id' => '借款人',
            'car_id' => '置换车辆',
            'car_id_new' => '新置换车辆',
            'apply_time' => '申请时间',
            'manager_id' => '提报人',
            'remark' => '备注',
            'audit_at' => '申批的时间',
            'audit_by' => '申批人员ID',
            'status' => '状态',
            'order' => '排序',
            'created_at' => '创建时间',
            'updated_at' => '更新时间',
            'created_by' => '录单员',
        ];
    }

    /**
     * @inheritdoc
     * @return \common\models\query\LoanCarChangeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\LoanCarChangeQuery(get_called_class());
    }

    public  function  behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
      //  return parent::behaviors(); // TODO: Change the autogenerated stub
    }
    public  function  getLoanCar()
    {
        return $this->hasOne(LoanCar::className(),['id'=>'car_id']);
    }
}
